# Generated by Django 3.0.8 on 2020-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='snipcart_api_key',
            field=models.CharField(default='', help_text='Your Snipcart public API key', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='contact_email',
            field=models.CharField(blank=True, default='only1meshhairline@gmail.com', max_length=255, null=True),
        ),
    ]
