# Generated by Django 3.0.8 on 2020-08-10 10:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
        ('shop', '0003_productfeaturedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategoryCollection',
            fields=[
                ('productcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.ProductCategory')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_categories', to='shop.Collection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('shop.productcategory', models.Model),
        ),
        migrations.CreateModel(
            name='CategoryCollectionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_collections', to='shop.Collection')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_pages', to='shop.ProductCategory')),
            ],
            options={
                'unique_together': {('page', 'product_category')},
            },
        ),
    ]
