# Generated by Django 3.0.8 on 2020-08-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('shop', '0004_categorycollection_categorycollectionmap_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryCollection',
        ),
    ]
