# Generated by Django 3.0.8 on 2020-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_collectionfeaturedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='default_currency_symbol',
            field=models.CharField(default='N', help_text='Default should be naira symbol', max_length=3),
        ),
    ]
