# Generated by Django 3.0.8 on 2020-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200924_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='exchange_rate',
            field=models.IntegerField(default=380, help_text='1USD in NGN'),
        ),
    ]
