# Generated by Django 3.0.8 on 2020-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopsettings_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=10),
        ),
    ]
