kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicdmeshhairline
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cicdmeshhairline
    namespace: default
roleRef:
  kind: Role
  name: cicdmeshhairline
  apiGroup: rbac.authorization.k8s.io
